PORT: "8081"
EMAIL_PASSWORD: "majbsqfzgpgzbuaq"
EMAIL_NAME: "baby.university09@gmail.com"
BASE_URI_TAX: "http://35.168.10.29:4000"
BASE_URI_EMPLOYEE: "http://35.168.10.29:8080"
BASE_URI_INSURANCE: "http://35.168.10.29:4001"
CLIENT_EMAIL_NAME: "theo.pham@alphaplussolution.com.au"
BUCKET_NAME: "tavola-italiano-res"
BLOB_NAME: "salary.csv"